name: 'Habbo Resource'

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
        
    - name: Test
      run: go test -v ./...

    - name: Install Go
      run: make install && hat

    - name: Download Habbo.swf
      run: hat habboswf

    - name: Download Articles
      run: hat articles

    - name: Download Clothes
      run: hat clothes

    - name: Download Furnitures Icons
      run: hat furni icons

    - name: Download Furnitures
      run: hat furni

    - name: Download Badges
      run: hat badges

    - name: Download Effects
      run: hat effects

    - name: Download Badgeparts
      run: hat badgeparts

    - name: Download MP3
      run: hat mp3

    - name: Download Icons
      run: hat icons

    - name: Download Pets
      run: hat mp3

    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        add: resource

    - name: Tar files
      run: tar -cvf resource.tar ./resource

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Habbo Resource
        path: resource.tar
