name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
        
    - name: Test
      run: go test -v ./...

    - name: Install Go
      run: make install && hat

    - name: Make resource directory
      run: mkdir resource

    - name: Download Habbo.swf
      run: hat habboswf -o ./resource

    - name: List
      run: ls
