name: "Habbo Resource"

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: hat

      - uses: actions/checkout@v4
        with:
          repository: izzxt/habbo-resource
          token: ${{ secrets.GH_PAT }}
          path: resource

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: List files
        run: ls -l

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
          cache: true
          cache-dependency-path: hat

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        run: make build && hat

  download_habbo_swf:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Habbo SWF
        run: hat habboswf
