name: 'Release'

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
        workdir: ./cmd/hat
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
